semantic_label_name_map = {
    "conll2003": {"ner_tags_short": {
        "O": "outside",
        "PER": "person",
        "LOC": "location",
        "ORG": "organization",
        "MISC": "miscellaneous",
    }, "ner_tags_long": {
        "O": "outside",
        "PER": "persons such as actors, athletes, politicians, or scholars",
        "LOC": "locations such as cities, states, countries, and political entities",
        "ORG": "organizations such as companies, schools, or governments",
        "MISC": "other entities that do not belong to any of the other entity subtypes",
    }},
    "wnut_17": {"ner_tags_short": {
        "O": "outside",
        "corporation": "corporation",
        "creative-work": "creative work",
        "group": "group",
        "location": "location",
        "person": "person",
        "product": "product",
    }, "ner_tags_long": {
        "O": "outside",
        "corporation": "corporations such as companies, agencies, or institutions",
        "creative-work": "creative works such as books, movies, or songs",
        "group": "groups such as sports teams, political parties, or bands",
        "location": "locations such as cities, states, countries, or political entities",
        "person": "persons such as actors, athletes, politicians, or scholars",
        "product": "products such as cars, airplanes, or software",
    }},
    "jnlpba": {"ner_tags_short": {
        "O": "outside",
        "DNA": "DNA",
        "RNA": "RNA",
        "cell_line": "cell line",
        "cell_type": "cell type",
        "protein": "protein",
    }, "ner_tags_long": {
        "O": "outside",
        "DNA": "DNA sequences such as genes or chromosomes",
        "RNA": "RNA sequences such as mRNA or tRNA",
        "cell_line": "cell line such as HeLa or HEK293",
        "cell_type": "cell type such as fibroblasts or neurons",
        "protein": "proteins such as enzymes, hormones, or antibodies",
    }},
    "conll2012_ontonotesv5": {
        "ner_tags_short": {
            "O": "outside",
            "CARDINAL": "cardinal",
            "DATE": "date",
            "EVENT": "event",
            "FAC": "facility",
            "GPE": "geographical social political entity",
            "LANGUAGE": "language",
            "LAW": "law",
            "LOC": "location",
            "MONEY": "money",
            "NORP": "nationality religion political",
            "ORDINAL": "ordinal",
            "ORG": "organization",
            "PERCENT": "percent",
            "PERSON": "person",
            "PRODUCT": "product",
            "QUANTITY": "quantity",
            "TIME": "time",
            "WORK_OF_ART": "work of art",
        },
        "ner_tags_long": {
            "O": "outside",
            "CARDINAL": "numerals that do not fall under another type",
            "DATE": "absolute or relative dates or periods",
            "EVENT": "named hurricanes, battles, wars, sports events, etc.",
            "FAC": "buildings, airports, highways, bridges, etc.",
            "GPE": "geographical entities such as countries, cities or states",
            "LANGUAGE": "any named language",
            "LAW": "named documents made into laws",
            "LOC": "non-political locations, mountain ranges, bodies of water",
            "MONEY": "monetary values including unit such as currencies",
            "NORP": "nationality religion political",
            "ORDINAL": "a number defining the rank of something such as first or second",
            "ORG": "named corporate, governmental, or other organizational entities",
            "PERCENT": "percentages including % and fraction",
            "PERSON": "persons including fictional characters",
            "PRODUCT": "products made or sold by companies",
            "QUANTITY": "measurements including unit such as weight or distance",
            "TIME": "times including date, time, and duration",
            "WORK_OF_ART": "art entities such as titles of books, songs, etc.",
        }
    },
    "few-nerd": {
        "ner_tags": {
            "O": "outside",
            "location": "location",
            "person": "person",
            "organization": "organization",
            "building": "building",
            "other": "other",
            "product": "product",
            "event": "event",
            "art": "art",
        },
        "ner_tags_short": {
            "O": "outside",
            "location": "location",
            "person": "person",
            "organization": "organization",
            "building": "building",
            "other": "other",
            "product": "product",
            "event": "event",
            "art": "art",
        },
        "ner_tags_long": {
            "O": "outside",
            "location": "locations such as cities, states, countries, and political entities",
            "person": "persons such as actors, athletes, politicians, or scholars",
            "organization": "organizations such as companies, schools, or governments",
            "building": "buildings such as airports, hospitals, or libraries",
            "other": "other entities such as languages, diseases, or educational degrees",
            "product": "products such as cars, airplanes, or software",
            "event": "events such as elections, protests, or disasters",
            "art": "art forms such as music, films, or paintings",
        },
        "fine_ner_tags_long":
        {
            "O": "outside",
            "location-GPE": "geographical entity such as cities, states, countries, and political entities",
            "person-other": "persons that do not belong to any of the other person subtypes",
            "organization-other": "organizations such as foundations that do not belong to any of the other organization subtypes",
            "organization-company": "company, corporation, or business",
            "person-artist/author": "authors or artists mostly known for their work in the books or movies",
            "person-athlete": "athletes that are known for their participation in sports",
            "person-politician": "politicians such as presidents, senators, and other government officials",
            "building-other": "buildings that do not belong to any of the other building subtypes",
            "organization-sportsteam": "sport teams such as football, basketball, baseball, and hockey teams",
            "organization-education": "eduction institutions such as schools, colleges, and universities",
            "location-other": "locations that do not belong to any of the other location subtypes",
            "other-biologything": "biological entities such as proteins, or genes",
            "location-road/railway/highway/transit": "roads, railways, highways, or transit systems",
            "person-actor": "actors that are known for their work in movies or TV shows",
            "product-other": "products that do not belong to any other product subtypes",
            "event-sportsevent": "sports event such as the Super Bowl, World Series or Drafts",
            "organization-government/governmentagency": "governments and government agencies such as the US government",
            "location-bodiesofwater": "bodies of water such as rivers, lakes, or oceans",
            "organization-media/newspaper": "media or newspapers such as CNN, Fox News, or New York Times",
            "art-music": "music such as songs or albums",
            "other-chemicalthing": "chemical entities such as chemicals or drugs",
            "event-attack/battle/war/militaryconflict": "attacks, battles, wars, or military conflicts",
            "organization-politicalparty": "political parties such as the Democratic Party or Republican Party",
            "art-writtenart": "written art such as books or poems",
            "other-award": "awards such as the Nobel Prize or Oscars",
            "other-livingthing": "living objects such as species or animals",
            "event-other": "other events such as festivals",
            "art-film": "films such as movies or TV shows",
            "product-software": "software such as Microsoft Word or Google Chrome",
            "organization-sportsleague": "sport leagues such as the NFL, NBA or MLB",
            "other-language": "languages such as English or Spanish",
            "other-disease": "diseases such as cancer, diabetes or pandemics",
            "organization-showorganization": "show organizations such as bands",
            "product-airplane": "airplanes such as Boeing 747 or Airbus A380",
            "other-astronomything": "astronomy objects such as planets or stars",
            "organization-religion": "religions such as Christianity or Islam",
            "product-car": "cars such as Tesla Model 3 or Toyota Camry",
            "person-scholar": "scholars such as scientists or professors",
            "other-currency": "currencies such as US Dollar or Euro",
            "person-soldier": "soldiers such as generals or lieutenants",
            "location-mountain": "mountains such as Mount Everest or Mount Fuji",
            "art-broadcastprogram": "broadcast program such as TV shows or radio shows",
            "location-island": "islands and other land masses surrounded by water",
            "art-other": "art forms such as theater or dance",
            "person-director": "directors that are known for their work in movies or TV shows",
            "product-weapon": "weapons such as guns or knives",
            "other-god": "gods such as Zeus or Odin",
            "building-theater": "theaters such as the state operas or metropolitan opera",
            "other-law": "law, acts, and legal documents",
            "product-food": "food items such as dunkin donuts",
            "other-medical": "medical entities such as medical conditions or medical procedures",
            "product-game": "games such as video games or board games",
            "location-park": "parks such as Central Park or Hyde Park",
            "product-ship": "ships such as command ships or aircraft carriers",
            "building-sportsfacility": "sports facilities such as stadiums or arenas",
            "other-educationaldegree": "educational degrees such as doctor titles, bachelor's degrees or master's degrees",
            "building-airport": "airports such as JFK Airport or LAX Airport",
            "building-hospital": "hospitals such as the Mayo Clinic or Cleveland Clinic",
            "product-train": "trains or railcars such as the Amtrak or Eurostar",
            "building-library": "libraries in universities, schools or cities",
            "building-hotel": "hotel chains such as the Hilton or Marriott",
            "building-restaurant": "restaurant or food chains such as McDonald's or Burger King",
            "event-disaster": "disasters such as earthquakes or hurricanes",
            "event-election": "elections such as the US presidential election or UK general election",
            "event-protest": "protests such french revolution or occupy wall street",
            "art-painting": "paintings such as the Mona Lisa or The Starry Night",
        },
        "fine_ner_tags_short":
        {
            "O": "outside",
            "location-GPE": "geographical social political entity",
            "person-other": "other person",
            "organization-other": "other organization",
            "organization-company": "company",
            "person-artist/author": "author artist",
            "person-athlete": "athlete",
            "person-politician": "politician",
            "building-other": "other building",
            "organization-sportsteam": "sportsteam",
            "organization-education": "eduction",
            "location-other": "other location",
            "other-biologything": "biology",
            "location-road/railway/highway/transit": "road railway highway transit",
            "person-actor": "actor",
            "product-other": "other product",
            "event-sportsevent": "sportsevent",
            "organization-government/governmentagency": "government agency",
            "location-bodiesofwater": "bodies of water",
            "organization-media/newspaper": "media newspaper",
            "art-music": "music",
            "other-chemicalthing": "chemical",
            "event-attack/battle/war/militaryconflict": "attack war battle military conflict",
            "organization-politicalparty": "political party",
            "art-writtenart": "written art",
            "other-award": "award",
            "other-livingthing": "living thing",
            "event-other": "other event",
            "art-film": "film",
            "product-software": "software",
            "organization-sportsleague": "sportsleague",
            "other-language": "language",
            "other-disease": "disease",
            "organization-showorganization": "show organization",
            "product-airplane": "airplane",
            "other-astronomything": "astronomy",
            "organization-religion": "religion",
            "product-car": "car",
            "person-scholar": "scholar",
            "other-currency": "currency",
            "person-soldier": "soldier",
            "location-mountain": "mountain",
            "art-broadcastprogram": "broadcastprogram",
            "location-island": "island",
            "art-other": "other art",
            "person-director": "director",
            "product-weapon": "weapon",
            "other-god": "god",
            "building-theater": "theater",
            "other-law": "law",
            "product-food": "food",
            "other-medical": "medical",
            "product-game": "game",
            "location-park": "park",
            "product-ship": "ship",
            "building-sportsfacility": "sportsfacility",
            "other-educationaldegree": "educational degree",
            "building-airport": "airport",
            "building-hospital": "hospital",
            "product-train": "train",
            "building-library": "library",
            "building-hotel": "hotel",
            "building-restaurant": "restaurant",
            "event-disaster": "disaster",
            "event-election": "election",
            "event-protest": "protest",
            "art-painting": "painting",
        },
        "fine_ner_tags_simple":
            {'O': 'XO',
             'location-GPE': 'PH',
             'person-other': 'UX',
             'organization-other': 'TG',
             'organization-company': 'VC',
             'person-artist/author': 'ZW',
             'person-athlete': 'LA',
             'person-politician': 'EX',
             'building-other': 'MK',
             'organization-sportsteam': 'XC',
             'organization-education': 'CE',
             'location-other': 'WP',
             'other-biologything': 'TN',
             'location-road/railway/highway/transit': 'CD',
             'person-actor': 'JQ',
             'product-other': 'YF',
             'event-sportsevent': 'QH',
             'organization-government/governmentagency': 'EU',
             'location-bodiesofwater': 'VH',
             'organization-media/newspaper': 'UK',
             'art-music': 'VL',
             'other-chemicalthing': 'PE',
             'event-attack/battle/war/militaryconflict': 'WC',
             'organization-politicalparty': 'TD',
             'art-writtenart': 'XE',
             'other-award': 'GF',
             'other-livingthing': 'KG',
             'event-other': 'EB',
             'art-film': 'SD',
             'product-software': 'YK',
             'organization-sportsleague': 'IJ',
             'other-language': 'XD',
             'other-disease': 'HR',
             'organization-showorganization': 'KQ',
             'product-airplane': 'QY',
             'other-astronomything': 'BM',
             'organization-religion': 'JW',
             'product-car': 'EN',
             'person-scholar': 'HG',
             'other-currency': 'LP',
             'person-soldier': 'WX',
             'location-mountain': 'WV',
             'art-broadcastprogram': 'GH',
             'location-island': 'TW',
             'art-other': 'RL',
             'person-director': 'DT',
             'product-weapon': 'KS',
             'other-god': 'KT',
             'building-theater': 'QT',
             'other-law': 'UD',
             'product-food': 'AY',
             'other-medical': 'JB',
             'product-game': 'XQ',
             'location-park': 'IS',
             'product-ship': 'ET',
             'building-sportsfacility': 'YL',
             'other-educationaldegree': 'WM',
             'building-airport': 'KL',
             'building-hospital': 'HM',
             'product-train': 'EK',
             'building-library': 'FZ',
             'building-hotel': 'RS',
             'building-restaurant': 'YN',
             'event-disaster': 'MQ',
             'event-election': 'VD',
             'event-protest': 'LV',
             'art-painting': 'NZ'
        }
    }
}
